# Generated by Django 2.1 on 2018-08-30 01:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateTimeField(default=datetime.datetime.today)),
                ('cantidadpersonas', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('No disponible', 'No disponible'), ('Disponible', 'Disponible'), ('Reservada', 'Reservada'), ('Confirmada', 'Confirmada')], default='Disponible', max_length=255)),
                ('horainicio', models.TimeField()),
                ('horafin', models.TimeField()),
                ('insumo', models.ManyToManyField(to='app.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sala'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
